const productData = {
	product: [
		{
			name: "Smartphone Wireless Charger",
			slug: "smartphone-wireless-charger",
			description:
				"A sleek, fast-charging wireless charger compatible with all Qi-enabled devices. Features overcharge protection and a non-slip surface.",
			price: 29,
			quantity: 200,
			sold: 120,
			shipping: 0,
			image: "../images/product images/poteable charger.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Bluetooth Headphones",
			slug: "bluetooth-headphones",
			description:
				"High-quality Bluetooth headphones with noise-cancellation and up to 20 hours of playtime. Comfortable fit and adjustable headband.",
			price: 89,
			quantity: 60,
			sold: 30,
			shipping: 5,
			image: "../images/product images/gameing mouse.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Bluetooth Earbuds",
			slug: "bluetooth-earbuds",
			description:
				"Compact and comfortable Bluetooth earbuds with noise cancellation and a long-lasting battery life of up to 20 hours.",
			price: 49,
			quantity: 150,
			sold: 80,
			shipping: 5,
			image: "../images/product images/bluetooth earbuds.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Smart Watch",
			slug: "smart-watch",
			description:
				"A stylish smart watch with a touch screen, fitness tracking, and notifications for calls and messages. Water-resistant and customizable watch faces.",
			price: 199,
			quantity: 75,
			sold: 45,
			shipping: 0,
			image: "../images/product images/smart watch.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Portable Power Bank",
			slug: "portable-power-bank",
			description:
				"High-capacity portable power bank with fast-charging capabilities and multiple USB ports for charging various devices simultaneously.",
			price: 39,
			quantity: 300,
			sold: 150,
			shipping: 0,
			image: "../images/product images/portable power bank.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Laptop Stand",
			slug: "laptop-stand",
			description:
				"Adjustable laptop stand made of durable aluminum with ergonomic design to improve posture and reduce neck strain.",
			price: 25,
			quantity: 100,
			sold: 60,
			shipping: 7,
			image: "../images/product images/laptop stand.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Wireless Mouse",
			slug: "wireless-mouse",
			description:
				"Ergonomic wireless mouse with a high-precision sensor and adjustable DPI settings. Ideal for both office and gaming use.",
			price: 35,
			quantity: 180,
			sold: 90,
			shipping: 5,
			image: "../images/product images/wireless mouse.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "USB-C Hub",
			slug: "usb-c-hub",
			description:
				"Multi-port USB-C hub with HDMI, USB 3.0, and SD card slots. Ideal for expanding connectivity options on laptops and tablets.",
			price: 45,
			quantity: 120,
			sold: 70,
			shipping: 5,
			image: "../images/product images/usb-c hub.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Smart Home Speaker",
			slug: "smart-home-speaker",
			description:
				"Voice-controlled smart speaker with high-quality sound and compatibility with various smart home systems.",
			price: 89,
			quantity: 50,
			sold: 30,
			shipping: 0,
			image: "../images/product images/smart home speaker.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "External SSD",
			slug: "external-ssd",
			description:
				"High-speed external SSD with 1TB storage capacity. Ideal for quick file transfers and secure data backup.",
			price: 149,
			quantity: 80,
			sold: 40,
			shipping: 0,
			image: "../images/product images/external ssd.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Fitness Tracker",
			slug: "fitness-tracker",
			description:
				"Advanced fitness tracker with heart rate monitoring, step counting, and sleep analysis. Syncs with mobile apps for detailed health insights.",
			price: 79,
			quantity: 130,
			sold: 60,
			shipping: 5,
			image: "../images/product images/fitness tracker.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Gaming Keyboard",
			slug: "gaming-keyboard",
			description:
				"Mechanical gaming keyboard with customizable RGB backlighting and programmable keys. Designed for enhanced gaming performance.",
			price: 99,
			quantity: 90,
			sold: 55,
			shipping: 0,
			image: "../images/product images/gaming keyboard.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Webcam",
			slug: "webcam",
			description:
				"High-definition webcam with built-in microphone and autofocus. Ideal for video conferencing and streaming.",
			price: 59,
			quantity: 110,
			sold: 85,
			shipping: 5,
			image: "../images/product images/webcam.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Portable Projector",
			slug: "portable-projector",
			description:
				"Compact and portable projector with high-definition display and built-in speakers. Perfect for presentations and home entertainment.",
			price: 299,
			quantity: 40,
			sold: 20,
			shipping: 0,
			image: "../images/product images/portable projector.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Cordless Vacuum Cleaner",
			slug: "cordless-vacuum-cleaner",
			description:
				"Powerful cordless vacuum cleaner with adjustable suction and a lightweight design. Ideal for quick and easy cleaning.",
			price: 179,
			quantity: 70,
			sold: 35,
			shipping: 0,
			image: "../images/product images/cordless vacuum cleaner.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Digital Photo Frame",
			slug: "digital-photo-frame",
			description:
				"Digital photo frame with a high-resolution display and Wi-Fi connectivity. Easily share and display your favorite photos.",
			price: 129,
			quantity: 60,
			sold: 25,
			shipping: 7,
			image: "../images/product images/digital photo frame.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
		{
			name: "Noise Cancelling Headphones",
			slug: "noise-cancelling-headphones",
			description:
				"Over-ear noise-cancelling headphones with superior sound quality and long battery life. Ideal for immersive listening experiences.",
			price: 149,
			quantity: 90,
			sold: 55,
			shipping: 0,
			image: "../images/product images/noise cancelling headphones.jpg",
			category: "66aaea4a3f7493a9c6d32965",
		},
	],
};

module.exports = {
	productData,
};
